### ISSUE TITLE
Re-render when someone back or forward by browser UI

### ISSUE THREAD

**Issue by kruczekrobert** [reactive-python/reactpy-router#20] opened 2023-06-16 16:09 UTC
Back and Forward don't re-render the page, which causes stuck on last render.

**Comment by rmorshea** [comment] 2023-06-16 17:14
Duplicate of: https://github.com/reactive-python/reactpy-router/issues/16

We just put out a release that should fix this.

**Closed by rmorshea** 2023-06-16 17:14 UTC
Labels: bug
